---
title: "pagedown::chrome_print() with Shinyapps"
output: html_document
params:
  N: "slider"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, fig.height=4, fig.width=10)
```

```{r include=FALSE}
theme_set(theme_bw())
```
  
```{r}
dt <- data.frame(value = rnorm(params$N))
```

## Summary statistics

```{r}
dt %>% 
  summarise(
    min = min(value),
    mean = mean(value),
    Std.Dev = sd(value),
    max = max(value)
  ) %>% 
  pivot_longer(everything()) %>% 
  data.table::data.table()
```

## Histogram

```{r}
ggplot(dt, aes(value)) +
  geom_histogram(fill = "steelblue", alpha = 0.7) +
  geom_vline(aes(xintercept = mean(value))) +
  geom_vline(aes(xintercept = mean(value)+sd(value)), linetype = "dashed") +
  geom_vline(aes(xintercept = mean(value)-sd(value)), linetype = "dashed")
```

## Box-plot

```{r}
ggplot(dt, aes(x = value, y = "")) +
  geom_boxplot(fill = "steelblue", alpha = 0.7) +
  geom_jitter(color = "orange", alpha = 0.5)
```

## qq-plot

```{r}
ggplot(dt, aes(sample = value)) +
  geom_qq() +
  geom_qq_line(color = "steelblue")
```

